public class Aula01ArrayMult {

	public static void main(String[] args) {

		int [] [] arrayMulti1 = new int [2] [2];
		arrayMulti1 [0] [0] = 22;
		arrayMulti1 [0] [1] = 35;
		arrayMulti1 [1] [0] = 60;
		arrayMulti1 [1] [1] = 55;
		System.out.println(arrayMulti1[0] [0]);
		System.out.println(arrayMulti1[0] [1]);
		System.out.println(arrayMulti1[1] [0]);
		System.out.println(arrayMulti1[1] [1]);
	}

}
